apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: benchmark
  labels:
    app: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 1Gi
            cpu: 100m
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname 
                labelSelector:
                  matchLabels:
                    app: nginx  
              weight: 100
      terminationGracePeriodSeconds: 10