apiVersion: v1
kind: Pod
metadata:
  name: canary-v2
  labels:
    name: canary-v2
spec:
  containers:
  - name: canary-v2
    image: gmlrhks95/canary-v2
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: v2-svc
spec:
  selector:
    name: canary-v2
  ports:
  - port: 80
    targetPort: 80